name: Minimal workflow for CI/CD
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

env:
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  builder_images:
    strategy:
      matrix:
        pgversion:
          - 14
          - 15
          - 16
          - 17
          - 18
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: update to docker-compose v2
        run: |
          sudo apt-get install -y curl
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.34.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: create rpms folder as required
        run: |
          mkdir -p rpms
          chmod 777 rpms

      - name: build rpm's
        run: |
          docker-compose up builder --exit-code-from builder
        env:
          PGVERSION: ${{ matrix.pgversion }}
